services:
  nvc:
    build:
      context: .
      args:
        NEXT_PUBLIC_CREATE_BASE_URL: ${NEXT_PUBLIC_CREATE_BASE_URL}
        NEXT_PUBLIC_CREATE_HOST: ${NEXT_PUBLIC_CREATE_HOST}
        NEXT_PUBLIC_PROJECT_GROUP_ID: ${NEXT_PUBLIC_PROJECT_GROUP_ID}
    container_name: nvc
    restart: unless-stopped
    ports:
      - "4003:4003"
    environment:
      NODE_ENV: production
      PORT: 4003
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      AUTH_URL: ${AUTH_URL}
      NEXT_PUBLIC_AUTH_URL: ${NEXT_PUBLIC_AUTH_URL}
      NEXT_PUBLIC_CREATE_BASE_URL: ${NEXT_PUBLIC_CREATE_BASE_URL}
      NEXT_PUBLIC_CREATE_HOST: ${NEXT_PUBLIC_CREATE_HOST}
      NEXT_PUBLIC_PROJECT_GROUP_ID: ${NEXT_PUBLIC_PROJECT_GROUP_ID}
